#ifndef MODULE__MODE
#define MODULE__MODE
enum MODE {
    MODE_IDX_FIRST_NG = 0,
    MODE_IDX_LAST_NG = 1,
    MODE_MULTI_BETWEEN_NEGATIVE = 2,
    MODE_MULTI_BEFORE_AND_AFTER_NEGATIVE = 3,
};
#endif